version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_portafolio_jhony
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_portafolio_jhony
      MYSQL_USER: user_jsaenzh
      MYSQL_PASSWORD: AngelaDobby1986
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
